#!/usr/bin/env python3
import argparse
import csv
import math
import re
from pathlib import Path

REQUIRED_COLUMNS = [
    "m12",  # legacy preserved
    "m12_2_used",
    "m12_2_gen_after_set",
    "delta_m12_2_gen_minus_used",
    "replay_semantics_version",
    "yukawa_type",
    "higgs_state",
    "model_api_path",
    "calc_engine",
    "git_commit",
    "git_dirty",
]


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def parse_float_finite(row: dict, key: str) -> float:
    value = float(row[key])
    require(math.isfinite(value), f"{key} is not finite: {row[key]}")
    return value


def significant_digits_scientific(raw: str) -> int:
    m = re.match(r"^[+-]?(\d)\.(\d+)[eE][+-]?\d+$", raw.strip())
    if not m:
        return 0
    return 1 + len(m.group(2))


def main() -> int:
    ap = argparse.ArgumentParser(description="Smoke-check replay-safe CSV contract fields")
    ap.add_argument("--csv", required=True, help="Path to CSV generated by PhysScanWithFixings")
    ap.add_argument("--min-significant-digits", type=int, default=17)
    ap.add_argument("--expected-yukawa-type", type=int, default=1)
    ap.add_argument("--expected-higgs-state", default="h2/DECAY35")
    args = ap.parse_args()

    csv_path = Path(args.csv)
    require(csv_path.exists(), f"CSV not found: {csv_path}")

    with csv_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        header = reader.fieldnames or []
        for col in REQUIRED_COLUMNS:
            require(col in header, f"Missing required column: {col}")

        rows = list(reader)

    require(len(rows) > 0, "CSV has no data rows")
    row = rows[0]

    require(str(row["replay_semantics_version"]).strip() != "", "replay_semantics_version is empty")

    m12_used = parse_float_finite(row, "m12_2_used")
    delta = parse_float_finite(row, "delta_m12_2_gen_minus_used")

    sig_m12_used = significant_digits_scientific(row["m12_2_used"])
    sig_delta = significant_digits_scientific(row["delta_m12_2_gen_minus_used"])
    require(sig_m12_used >= args.min_significant_digits,
            f"m12_2_used precision too low: raw='{row['m12_2_used']}', sig_digits={sig_m12_used}")
    require(sig_delta >= args.min_significant_digits,
            f"delta_m12_2_gen_minus_used precision too low: raw='{row['delta_m12_2_gen_minus_used']}', sig_digits={sig_delta}")

    ytype = int(float(row["yukawa_type"]))
    require(ytype == args.expected_yukawa_type,
            f"Unexpected yukawa_type: got {ytype}, expected {args.expected_yukawa_type}")

    require(row["higgs_state"].strip() == args.expected_higgs_state,
            f"Unexpected higgs_state: got '{row['higgs_state']}', expected '{args.expected_higgs_state}'")

    require(row["model_api_path"].strip() != "", "model_api_path is empty")
    require(row["calc_engine"].strip() != "", "calc_engine is empty")

    print("OK replay-safe smoke checks")
    print(f"csv={csv_path}")
    print(f"rows={len(rows)}")
    print(f"m12_2_used={m12_used:.17e}")
    print(f"delta_m12_2_gen_minus_used={delta:.17e}")
    print(f"sig_digits_m12_2_used={sig_m12_used}")
    print(f"sig_digits_delta={sig_delta}")
    print(f"replay_semantics_version={row['replay_semantics_version']}")
    print(f"yukawa_type={ytype}")
    print(f"higgs_state={row['higgs_state']}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
